spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://xxxxxxxxxxx:5432/tour_of_heroes
    driver-class-name: org.postgresql.Driver
    username:
    password:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
